# -*- coding: utf-8 -*-
"""ner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Od3LBbMfe8Wrjbl6CbqXvvqiTg8CCvE
"""

import re
import sys
import getopt
import os


print(sys.argv)
print(sys.argv[1])

inputfile = sys.argv[1]

try:
    with open(inputfile) as file_in:
        SAMPLE_TEXT = []
        for line in file_in:
            SAMPLE_TEXT.append(line)

except IOError:
    print("Error: File does not appear to exist.")

try:
    with open("locations.txt") as file_in:
        LOCATIONS = []
        for line in file_in:
            LOCATIONS.append(line)
except IOError:
    print("Error: File does not appear to exist.")

try:
    with open("organizations.txt") as file_in:
        ORGANIZATION = []
        for line in file_in:
            ORGANIZATION.append(line)
except IOError:
    print("Error: File does not appear to exist.")

try:
    with open("PERSON.txt") as file_in:
        PERSON = []
        for line in file_in:
            PERSON.append(line)
except IOError:
    print("Error: File does not appear to exist.")


count = 0

for line in SAMPLE_TEXT:

    count = count+1
    countline = "Line:" + str(count)

# RULE EXAMPLE 1   ### Ankara'dan 'nın 'nin 'da 'den
    for name in re.findall(r"(([A-ZÇĞİÖŞÜ][a-zçğıöşü]+ *)+)(?='d?n?[aeıiuüoö]n?)", line):
        line = re.sub(r''.join(name), "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind("'")]
        if name in ORGANIZATION:
            print(countline + " ORGANIZATION", name)
        elif name in LOCATIONS:
            print(countline + " LOCATION", name)
        else:
            print(countline + " PERSON", name)

# RULE EXAMPLE 2   ### Hırvatistan Almanya Türkiye
    for name in re.findall(r"(([A-ZÇĞİÖŞÜ][a-zçğıöşü]+ *)+)(?=(istan)?y?[ae]?)", line):
        line = re.sub(r''.join(name) + "(istan)?y?[ae]?", "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind("'")]
        if name in LOCATIONS:
            print(countline + " LOCATION", name)

# RULE EXAMPLE 3   ### Kuzey Makedonya Güney Sudan Doğu Karadeniz Batı Almanya
    for name in re.findall(r"(Doğu)?(Batı)?(Kuzey)?(Güney)?[A-ZÇĞİÖŞÜ][a-zçğıöşü]*", line):
        line = re.sub(r''.join(name), "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind(" ")]
        print(countline + "LOCATION", name)

# RULE EXAMPLE 4   ### İyilik Vakfı -- Atatürkçüler Derneği -- Hava Kurumu
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]*(?=\s+Vakfı\w+)?(?=\s+Derneği\w+)?(?=\s+Kurumu\w+)?", line):
        print(countline + " ORGANIZATION", name)
        line = re.sub(r''.join(name), "", line)

# RULE EXAMPLE 5   ### Türk Milli Takımı
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* Milli [A-ZÇĞİÖŞÜ][a-zçğıöşü]* ", line):
        line = re.sub(r''.join(name), "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        line = re.sub(r''.join(name), "", line)
        print(countline + " ORGANIZATION", name)

# RULE EXAMPLE 6   ### 09/09/2020
    for name in re.findall(r"[0-9]{2}\/[0-9]{2}\/[0-9]{4}", line):
        line = re.sub(r''.join(name), "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind(" ")]
        print(countline + " DATE", name)

# RULE EXAMPLE 7   ### TÜBİTAK Başkanı
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* Baş?kanı? [A-ZÇĞİÖŞÜ][a-zçğıöşü]*", line):
        line = re.sub(r''.join(name), "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind(" ")]
        print(countline + "PERSON",name)

# RULE EXAMPLE 8   ### Merkez Mahallesi - Büyükdere Caddesi
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* (Cadde)?(Bulvar)?(Mahallesi)?\w+", line):
        line = re.sub(r''.join(name) + "(Cadde)?(Bulvar)?\w+", "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind(" ")]
        if name in LOCATIONS:
            print(countline + " LOCATION", name)
        elif name in ORGANIZATION:
            print(countline + " ORGANIZATION", name)
        else:
            print(countline + " PERSON", name)

# RULE EXAMPLE 9   ### Akhisarspor
    for name in re.findall(r"(([A-ZÇĞİÖŞÜ][a-zçğıöşü]+ *)+)(?=spor)", line):
        print(countline + "ORGANIZATION",name)
        line = re.sub(r''.join(name), "", line)

# RULE EXAMPLE 10   ### Başbakan istifa
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]*(?=\s+istifa)", line):
        print(countline + "PERSON", name)
        line = re.sub(r''.join(name), "", line)

# RULE EXAMPLE 11    ### AKUT ---- Dogru
    for name in re.findall(r"[A-ZÇĞİÖŞÜ]*", line):
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind(" ")]
        line = re.sub(r''.join(name), "", line)
        if name in ORGANIZATION:
            print(countline + " ORGANIZATION", name)

# RULE EXAMPLE 12  #### Maliye Müdürü Ali
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* Müdürü? [A-ZÇĞİÖŞÜ][a-zçğıöşü]*", line):
        print(countline + " PERSON", name)
        line = re.sub("Müdürü", "", line)

# RULE EXAMPLE 13  ##### 12 Kasım 2020
    for name in re.findall(r"\d\d\s[A-ZÇĞİÖŞÜ][a-zçğıöşü]*\s\d{4}", line):
        name = name[:name.rfind(" ")]
        print(countline + " DATE",name)
        line = re.sub(name, "", line)

# RULE EXAMPLE 14  CEO'su Tom Xxx
    for name in re.findall(r"(?<=CEO'su)\s[A-ZÇĞİÖŞÜ][a-zçğıöşü]*", line):
        name = re.sub("CEO'su", "", line)
        line = re.sub("CEO'su" + r''.join(name), "", line)
        print(countline + " PERSON", name)

# RULE EXAMPLE 15 #### Sabancı Üniversitesi
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* (Fakülte)?(Üniversite)?\w+", line):
        line = re.sub(r''.join(name), "", line)
        print(countline + " ORGANIZATION",name)

# RULE EXAMPLE 16  #### Ahmet Bey
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* (Bey)?(Hanım)?\w+", line):
        line = re.sub(r''.join(name), "", line)
        print(countline + " PERSON",name)

# RULE EXAMPLE 17 ## Adana Milletvekili
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* Milletvekil\w+", line):
        line = re.sub(r''.join(name) + "Milletvekil\w+", "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind(" ")]
        if name in LOCATIONS:
            print(countline + " LOCATION", name)

# RULE EXAMPLE 18  ## EXPO 2020
    for name in re.findall(r"[A-ZÇĞİÖŞÜ][a-zçğıöşü]* [0-9]*", line):
        line = re.sub(r''.join(name), "", line)
        if type(name) == type(("", "")):
            name = name[0]
            name = "".join(k for k in name)
        name = name[:name.rfind("'")]
        print(countline + " ORGANIZATION", name)

# RULE EXAMPLE 19 Ankara-İstanbul
    for name in re.findall(r"(([A-ZÇĞİÖŞÜ][a-zçğıöşü]+ *)+)(?=(-))*", line):
        line = re.sub(name, "", line)
        print(countline + " LOCATION",name)

# RULE EXAMPLE 20  9.Noter
    for name in re.findall(r"[0-9]*.[A-ZÇĞİÖŞÜ][a-zçğıöşü]*", line):
        line = re.sub(name, "", line)
        print(countline + " LOCATION", name)
